config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users

  namespace :admin do
    resources :statuses, except: :show
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :client
  belongs_to :service
  validates :street, :town, :zip, presence: true
  validates :zip, numericality: { only_integer: true, greater_than: 0, less_than: 99_999 }
  validates :zip, format: /^\d{5}$/
end

app/models/claim.rb
class Claim < ActiveRecord::Base
  belongs_to :operator
  belongs_to :client
  belongs_to :service
  belongs_to :location
  belongs_to :serviceman
  belongs_to :status
  has_many :comments
  has_many :waybills
  validates :client, :location, :valid, :closed, :stust, :description, presence: true
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :users
  has_many :claims
  has_one :address
  validates :phone, :email, presence: true
  validates :phone, numericality: { only_integer: true, greater_than: 0, less_than: 999_999_999 }
  validates :phone, format: /^\d{9}$/
  validates :email, format: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :claim
  validates :text, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :claims
  validates :name, presence: true
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  has_one :user
  has_many :claims
  validates :user, :name, :phone, :email, :user, presence: true
  validates :phone, numericality: { only_integer: true, greater_than: 0, less_than: 999_999_999 }
  validates :phone, format: /^\d{9}$/
  validates :email, format: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_one :address
  has_many :claims
  has_many :servicemen
  validates :phone, :email, presence: true
  validates :phone, numericality: { only_integer: true, greater_than: 0, less_than: 999_999_999 }
  validates :phone, format: /^\d{9}$/
  validates :email, format: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
end

app/models/serviceman.rb
class Serviceman < ActiveRecord::Base
  belongs_to :service
  has_many :claims
  validates :service, :name, :phone, :email, presence: true
  validates :phone, numericality: { only_integer: true, greater_than: 0, less_than: 999_999_999 }
  validates :phone, format: /^\d{9}$/
  validates :email, format: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :claims
  validates :name, presence: true
end

app/models/transport_service.rb
class TransportService < ActiveRecord::Base
  validates :phone, :email, :name, presence: true
  validates :phone, numericality: { only_integer: true, greater_than: 0, less_than: 999_999_999 }
  validates :phone, format: /^\d{9}$/
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :operator
  belongs_to :client
  has_many :comments
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/waybill.rb
class Waybill < ActiveRecord::Base
  belongs_to :transport_service
  belongs_to :claim
  validates :number, :transport_service, presence: true
end

app/controllers/admin/statuses_controller.rb
class Admin::StatusesController < ApplicationController
  before_action :authenticate_user!

  def index
    @statuses = Status.all
  end

  def new
    @status = Status.new
    authorize @status
  end

  def create
    @status = Status.new status_params
    authorize @status
    if @status.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def edit
    @status = Status.find params[:id]
    authorize @status
  end

  def update
    @status = Status.find params[:id]
    authorize @status
    if @status.update status_params
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def destroy
    @status = Status.find params[:id]
    authorize @status
    @status.destroy
    redirect_to admin_statuses_path
  end

  def status_params
    params.require(:status).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/admin/status_helper.rb
module Admin
  module StatusHelper
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/status/index.html.slim
- if policy(@statuses).create?
  .row.col-md-12
    = link_to :new, admin_new_status_path, { class: 'btn btn-primary' }

.row.col-md-12
  table.table.table-striped.table-hover
    thead
      tr
        th ID
        th Name
        - if policy(@brands).edit?
          th Edit
        - if policy(@brands).destroy?
          th Remove
    tbody
      - for status in @statuses do
        tr
          td = status.id
          td = status.name
          - if policy(@statuses).edit?
            td = link_to :Edit, admin_edit_status_path(brand), class: 'btn btn-primary'
          - if policy(@statuses).destroy?
            td = link_to :Remove, admin_status_path(brand), method: :delete, class: 'btn btn-danger'

app/views/admin/statuses/_form.html.slim
= simple_form_for [:admin, @status] do |f|
  = f.input :name, label: 'Name of Status'
  = f.button :submit, class: 'btn-primary'

app/views/admin/statuses/edit.html.slim
= render 'form'

app/views/admin/statuses/index.html.slim
- if policy(@statuses).create?
  .row.col-md-12
    = link_to :new, new_admin_status_path, { class: 'btn btn-primary' }

.row.col-md-12
  table.table.table-striped.table-hover
    thead
      tr
        th ID
        th Name
        - if policy(@statuses).edit?
          th Edit
        - if policy(@statuses).destroy?
          th Remove
    tbody
      - for status in @statuses do
        tr
          td = status.id
          td = status.name
          - if policy(@statuses).edit?
            td = link_to :Edit, edit_admin_status_path(status), class: 'btn btn-primary'
          - if policy(@statuses).destroy?
            td = link_to :Remove, admin_status_path(status), method: :delete, class: 'btn btn-danger'

app/views/admin/statuses/new.html.slim
= render 'form'

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.slim
- if user_signed_in?
  li = link_to 'Edit account', edit_user_registration_path
  li = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  li = link_to 'Sign in', new_user_session_path
  li = link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'
      ul.nav.navbar-nav.navbar-right
        == render 'layouts/nav_links_for_auth'

app/views/layouts/_navigation_links.html.slim
/ add navigation links to this file

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Transport Claims'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Transport Claims'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      .container
        == yield

app/views/visitors/index.html.erb
<h3>Welcome</h3>